version: "2"

services:
  debian_stretch:
    build:
      context: debian/stretch
    image: bibaijin/debian:stretch

  golang_1_8:
    build:
      context: golang/1.8
    image: bibaijin/golang:1.8
    depends_on:
      - debian_stretch

  haskell_8_2:
    build:
      context: haskell/8.2
    image: bibaijin/haskell:8.2
    depends_on:
      - debian_stretch
